CREATE TABLE [dbo].[TblParent] (
    [ParentID]        INT           IDENTITY (1, 1) NOT NULL,
    [FirstName]       VARCHAR (50)  NOT NULL,
    [LastName]        VARCHAR (50)  NOT NULL,
    [Email]           VARCHAR (100) NOT NULL,
    [Password]        VARCHAR (100) NULL,
    [MaritalStatusID] INT           NOT NULL,
    [GenderID]        INT           NOT NULL,
    [CNICNumber]      VARCHAR (20)  NOT NULL,
    [RelationShipID]  INT           NOT NULL,
    [DateOfBirth]     DATETIME      NOT NULL,
    [MailingAddress]  VARCHAR (150) NOT NULL,
    [CountryID]       INT           NOT NULL,
    [StateID]         INT           NOT NULL,
    [CityID]          INT           NOT NULL,
    [ZipCode]         INT           NOT NULL,
    [CellNumber]      VARCHAR (15)  NOT NULL,
    [TelephoneRes]    VARCHAR (15)  NULL,
    [TelephoneOffice] VARCHAR (15)  NULL,
    [JobDetail]       VARCHAR (500) NULL,
    [ProfilePicture]  VARCHAR (500) NULL,
    [IsActive]        BIT           CONSTRAINT [DF_TblParent_IsActive] DEFAULT ((1)) NOT NULL,
    [CreatedDate]     DATETIME      CONSTRAINT [DF_TblParent_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [UpdatedDate]     DATETIME      NULL,
    [IPAddress]       VARCHAR (50)  NULL,
    [IsDeleted]       BIT           CONSTRAINT [DF_TblParent_IsDeleted] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_TblParent] PRIMARY KEY CLUSTERED ([ParentID] ASC)
);

