//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Model.Context.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblGenGender
    {
        public int GenderID { get; set; }
        public string Gender { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    }
}
